# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Docker image name pattern"
        type: string
        default: "SOMETHING"
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      shell: bash
      run: |
        ls
        echo "$VARIABLE"
        echo "$ROOT"
      env:
        VARIABLE: ${{ inputs.name }}
        ROOT: ${{ github.workspace }}
